// Custom Askama template filters. Registered automatically by Askama when used
// as `{{ value|filter_name }}`. Numeric filters accept both `i64` and `&i64`
// (via Borrow) because Askama passes owned temporaries for arithmetic
// expressions and references for plain field access.
use crate::services::helpers;

/// Helper trait so numeric filters accept `i64`, `&i64`, and `&&i64` uniformly.
/// Askama emits different reference depths depending on the expression form.
pub trait ToI64 {
    fn to_i64(&self) -> i64;
}
impl ToI64 for i64 {
    fn to_i64(&self) -> i64 { *self }
}
impl<T: ToI64 + ?Sized> ToI64 for &T {
    fn to_i64(&self) -> i64 { (**self).to_i64() }
}

/// {{ amount|rupiah }} -> "1.500.000"
pub fn rupiah<T: ToI64>(amount: T) -> ::askama::Result<String> {
    Ok(helpers::format_rupiah(amount.to_i64()))
}

/// {{ dt|datetime }} -> "29 Jul 2026, 14:30"
pub fn datetime<T: AsRef<str>>(s: T) -> ::askama::Result<String> {
    Ok(helpers::format_datetime(s.as_ref()))
}

/// {{ dt|date }} -> "29 Jul 2026"
pub fn date<T: AsRef<str>>(s: T) -> ::askama::Result<String> {
    Ok(helpers::format_date(s.as_ref()))
}

/// {{ text|truncate_chars(80) }}
pub fn truncate_chars<T: AsRef<str>>(s: T, n: usize) -> ::askama::Result<String> {
    Ok(helpers::truncate(s.as_ref(), n))
}

/// {{ content|richtext }} -> paragraph-wrapped, escaped HTML (marked safe).
pub fn richtext<T: AsRef<str>>(s: T) -> ::askama::Result<String> {
    Ok(helpers::safe_html(s.as_ref()))
}

/// {{ "cart"|icon|safe }} -> inline custom line-icon SVG (currentColor).
/// Always pair with `|safe`; the markup is trusted (generated by us).
pub fn icon<T: AsRef<str>>(name: T) -> ::askama::Result<String> {
    Ok(crate::icons::svg(name.as_ref()))
}

/// {{ text|json_str }} -> a JSON-escaped string value **without** surrounding
/// quotes, safe to embed inside a single-quoted HTML attribute that already
/// holds a JSON object (e.g. data-edit='{"name":"{{ v|json_str }}"}').
/// Escapes JSON control chars plus the HTML-attribute breakers `'`, `"`, `<`,
/// `>` and `&` using JSON `\uXXXX` sequences so the attribute stays intact.
pub fn json_str<T: AsRef<str>>(s: T) -> ::askama::Result<String> {
    let mut out = String::with_capacity(s.as_ref().len() + 8);
    for ch in s.as_ref().chars() {
        match ch {
            '"' => out.push_str("\\u0022"),
            '\'' => out.push_str("\\u0027"),
            '<' => out.push_str("\\u003c"),
            '>' => out.push_str("\\u003e"),
            '&' => out.push_str("\\u0026"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    Ok(out)
}
